# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'UA-138510892-1'

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'twitter', title: 'Twitter', link: 'https://twitter.com/apporima'}
- {icon: 'linkedin', title: 'LinkedIn', link: 'https://www.linkedin.com/in/bryanttn/'}
- {icon: 'github', title: 'GitHub', link: 'https://github.com/trevorbryant'}
- {icon: 'calendar', title: 'Calendar', link: '/busy'}
- {icon: 'file', title: 'Talks', link: '/talks'}
- {icon: 'pencil-square', title: 'Writeups', link: '/writeups'}

# Customize site text
pagination:
  next_page: 'newer'
  previous_page: 'older'
